bookies_core:
    resource: "@BookiesCoreBundle/Controller/"
    type:     annotation
    prefix:   /

bookies_api_order:
    type:     rest
    resource: Bookies\CoreBundle\Controller\OrdersController
    prefix: /api