bookies_order:
    resource: Bookies\CoreBundle\Controller\OrderController
    type:     annotation
    prefix:   /

bookies_orderline:
    resource: Bookies\CoreBundle\Controller\OrderLineController
    type:     annotation
    prefix:   /
    
bookies_api_order:
    type:     rest
    resource: Bookies\CoreBundle\Controller\ApiController
    prefix: /api
    
bookies_amazon:
    type:     rest
    resource: Bookies\CoreBundle\Controller\AmazonController
    prefix: /amazon